name: Steam Price Checker CI

on:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{github.workspace}}/build
            ${{github.workspace}}/build/${{env.BUILD_TYPE}}

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build directory
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{github.workspace}}/build

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
